### ISSUE TITLE
one master not supported

### ISSUE THREAD

**Issue by ahaurw01** [dcos/packet-terraform#10]
I tried creating a cluster with only one master and the web ui did not start. Digging further, I saw that the dcos spartan logs showed:

```
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]: [INFO] Clearing proxy environment variables
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]: [INFO] No zk.pid last mtime found at /var/lib/dcos/bootstrap/exhibitor_pid_stat
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]: [INFO] Shortcut failed, waiting for exhibitor to bring up zookeeper and stabilize
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]: [INFO] Expected cluster size: 3
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]: [INFO] Waiting for ZooKeeper cluster to stabilize
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]: [INFO] Starting new HTTP connection (1): 127.0.0.1
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]: Traceback (most recent call last):
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]:   File "/opt/mesosphere/bin/bootstrap", line 11, in <module>
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]:     load_entry_point('dcos-internal-utils==0.0.1', 'console_scripts', 'bootstrap')()
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]:   File "/opt/mesosphere/lib/python3.5/site-packages/dcos_internal_utils/cli.py", line 81, in main
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]:     exhibitor.wait(opts.master_count)
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]:   File "/opt/mesosphere/lib/python3.5/site-packages/dcos_internal_utils/exhibitor.py", line 103, in wait
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]:     raise Exception(msg)
Dec 01 13:33:04 packet-dcos-master-00 bootstrap[19251]: Exception: Expected 3 servers and 1 leader, got 1 servers and 1 leaders
Dec 01 13:33:04 packet-dcos-master-00 systemd[1]: dcos-spartan.service: Control process exited, code=exited status=1
Dec 01 13:33:04 packet-dcos-master-00 systemd[1]: Failed to start DNS Dispatcher: An RFC5625 Compliant DNS Forwarder.
Dec 01 13:33:04 packet-dcos-master-00 systemd[1]: dcos-spartan.service: Unit entered failed state.
Dec 01 13:33:04 packet-dcos-master-00 systemd[1]: dcos-spartan.service: Failed with result 'exit-code'.
```

I figured the important bit was `Exception: Expected 3 servers and 1 leader, got 1 servers and 1 leaders`. Not knowing where this is configured, I just tried creating a new cluster with 3 masters and that seemed to get things working so far.

Is one master not supposed to be supported here? Or is there a fix that can get one master cooking properly?

**Comment by crunchywelch** [comment]
this is probably a better question for the dcos team, but I do think I've done a cluster with one master in the past so not sure why this error crops up. if three masters is a requirement, we should enforce that.

**Comment by ahaurw01** [comment]
Fair enough. Maybe the sticking point was that I configured terraform to have one master, but the DNS business was for some reason expecting three.

```
dcos_master_count = "1"
```
